# fly.toml app configuration file generated for calorie-go-bot on 2025-08-01T10:34:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'calorie-go-bot'
primary_region = 'yyz'

[build]
  [build.args]
    GO_VERSION = '1.24.3'

[deploy]
  strategy = 'immediate'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
